"""Builds figures 5 (zoom of predicted-score histogram on the upper tail)
and 6 (cumulative count of consecutive AES deltas under each threshold).

Re-runnable. Overwrites the two target PNGs under
`notebooks/figures/`. Both PNGs are saved at 300 dpi.

Lihi's formal-report convention: figures are saved WITHOUT in-figure
titles (the caption goes in the report text). For informal use (slides,
this notebook's inline view) pass `--with-title` to keep the title +
insight subtitle baked into the PNG; the file is then suffixed
`_titled.png` so the formal version is never overwritten.
"""
from __future__ import annotations

import argparse

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

NB_DIR = Path(__file__).parent
RUN_DIR = NB_DIR / ".." / "runs" / "run_001_seed_42"
FIG_DIR = NB_DIR / "figures"

# Retroactive 80/20 split from the PS0 plan -- random_state=42, no
# stratification. The full predictions.csv was generated by datafan07's
# 15-fold CV on the full train.csv, so every prediction is technically
# OOF; this split just isolates a 20% slice for the "fig6 on test only"
# view that the PS0 plan envisioned.
TEST_SIZE = 0.20
SPLIT_SEED = 42


def isolate_test_slice(df: pd.DataFrame) -> pd.DataFrame:
    """Return the 20% test slice per the PS0-defined split."""
    train_idx, test_idx = train_test_split(
        np.arange(len(df)),
        test_size=TEST_SIZE,
        random_state=SPLIT_SEED,
    )
    return df.iloc[test_idx].copy()


def build_fig5_zoom(df: pd.DataFrame, with_title: bool = False) -> Path:
    """Zoom of fig2a on the upper tail [4.5, 6.5].

    Bin width 0.05 (fine enough to separate the upper-tail clusters).
    Emphases:
      1. Per-bin count label above each bar.
      2. Inset stat box (bucket counts) at upper-center.
    """
    preds = df["predicted_score"]

    fig, ax = plt.subplots(figsize=(11, 6))
    bins = np.arange(4.5, 6.55, 0.05)
    counts, edges, patches = ax.hist(
        preds, bins=bins, edgecolor="black", linewidth=0.5, color="#4c72b0", alpha=0.85
    )

    # Per-bin count label (skip empty bins)
    for c, e0, e1 in zip(counts, edges[:-1], edges[1:]):
        if c > 0:
            ax.text(
                (e0 + e1) / 2.0,
                c + max(counts) * 0.01,
                f"{int(c)}",
                ha="center",
                va="bottom",
                fontsize=8,
                color="black",
            )

    n_above_5_9 = int((preds >= 5.9).sum())
    n_above_6_0 = int((preds >= 6.0).sum())
    n_below_4_5 = int((preds < 4.5).sum())
    n_total = len(preds)

    ax.set_xlim(4.5, 6.5)
    ax.set_xlabel("Predicted score (AES OOF)")
    ax.set_ylabel("Essay count")
    if with_title:
        ax.set_title(
            "Figure 5 -- Zoom of predicted-score distribution, upper tail [4.5, 6.5]\n"
            f"True-score-6 territory is sparsely populated: only {n_above_5_9} essays predicted >=5.9, "
            f"{n_above_6_0} predicted >=6.0  (out of {n_total:,})",
            fontsize=11,
        )
    ax.grid(axis="y", alpha=0.3)

    # Inset stat box -- upper center
    stat_text = (
        f"Bucket counts (predicted score):\n"
        f"  [4.5, 5.0):  {int(((preds>=4.5)&(preds<5.0)).sum()):>5}\n"
        f"  [5.0, 5.5):  {int(((preds>=5.0)&(preds<5.5)).sum()):>5}\n"
        f"  [5.5, 5.9):  {int(((preds>=5.5)&(preds<5.9)).sum()):>5}\n"
        f"  [5.9, 6.0):  {int(((preds>=5.9)&(preds<6.0)).sum()):>5}\n"
        f"  >= 6.0:      {n_above_6_0:>5}\n"
        f"  (omitted < 4.5: {n_below_4_5:,})"
    )
    ax.text(
        0.5,
        0.98,
        stat_text,
        transform=ax.transAxes,
        va="top",
        ha="center",
        fontsize=9,
        family="monospace",
        bbox=dict(boxstyle="round,pad=0.4", facecolor="white", edgecolor="grey", alpha=0.9),
    )

    name = "fig5_predicted_zoom_upper_tail"
    out = FIG_DIR / (f"{name}_titled.png" if with_title else f"{name}.png")
    fig.tight_layout()
    fig.savefig(out, dpi=300, bbox_inches="tight")
    plt.close(fig)
    return out


def build_fig6_delta_cdf(df: pd.DataFrame, with_title: bool = False) -> Path:
    """Cumulative bar chart -- count of consecutive AES deltas below threshold.

    Operates on all 17,307 OOF predictions. The 15-fold CV already
    treats every essay as held-out for its own fold, so the merged
    `predictions.csv` is the natural unit of analysis -- no further
    slicing makes the figure more informative.
    Thresholds: 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05.
    """
    preds_sorted = df["predicted_score"].sort_values(ascending=False).reset_index(drop=True)
    delta = -preds_sorted.diff().dropna()
    total = len(delta)

    thresholds = [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05]
    counts = [int((delta < t).sum()) for t in thresholds]
    pcts = [100.0 * c / total for c in counts]
    labels = [f"< {t:g}" for t in thresholds]

    fig, ax = plt.subplots(figsize=(11, 6))
    xs = np.arange(len(thresholds))
    ax.bar(xs, pcts, color="#4c72b0", edgecolor="black", linewidth=0.6, alpha=0.9)

    ax.set_ylim(0, 100)
    ax.yaxis.set_major_formatter(plt.matplotlib.ticker.PercentFormatter(decimals=0))

    ax.set_xticks(xs)
    ax.set_xticklabels(labels)
    ax.set_xlabel("Consecutive score difference")
    ax.set_ylabel("Percentage of essay pairs")
    if with_title:
        ax.set_title(
            "Figure 6 -- AES predictions are densely packed\n"
            "Sort the 17,307 OOF predictions by predicted score; the gap between rank i and rank i+1 "
            f"is below 0.001 for {pcts[2]:.1f}% of the {total:,} consecutive pairs",
            fontsize=11,
        )
    ax.grid(axis="y", alpha=0.3)

    name = "fig6_aes_delta_cumulative"
    out = FIG_DIR / (f"{name}_titled.png" if with_title else f"{name}.png")
    fig.tight_layout()
    fig.savefig(out, dpi=300, bbox_inches="tight")
    plt.close(fig)
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--with-title",
        action="store_true",
        help="Also bake the in-figure title + insight subtitle into the PNG. "
             "Saves to *_titled.png (the title-less version is untouched).",
    )
    args = parser.parse_args()

    df = pd.read_csv(RUN_DIR / "stage_1_aes" / "predictions.csv")
    out5 = build_fig5_zoom(df, with_title=args.with_title)
    out6 = build_fig6_delta_cdf(df, with_title=args.with_title)
    print(f"wrote {out5}")
    print(f"wrote {out6}")


if __name__ == "__main__":
    main()
